version: "3.9"

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  social-media-api:
    container_name: social-media-api
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/var/www/api
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      DB_DEVELOPMENT: ${DB_DEVELOPMENT}
      DB_PRODUCTION: ${DB_PRODUCTION}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
